---
title: "Predict win/lose of each game of March Madness for year 2018"
author: "Team Scorpion - June Kim (jkim654), Hoyin Lau (hlau4), Xiaomei Sun (xsun56), Taiga Hasegawa (taigah2), Leo Franco Soto (francst2)"
date: "5/5/2019"
output: pdf_document
---

## Introduction 
The NCAA Division I Men's Basketball Tournament, also known as NCAA March Madness happens every year in spring. It features 68 college basketball teams from Division I level of the National Collegiate Atheletic Association (NCAA) to determine the national championship. March Madness was first created in 1939 by the National Association of Basketball Coaches and was pitched by Harold Olsen. 

The format of the tournament are in rounds in the following order (taken from wikipedia.org/wiki/NCAA_Division_I_Men's_Basketball_Tournament):

- The First Four
- The First Round (the Round of 64)
- The Second Round (the Round of 32)
- The Regional Semi-finals (participating teams are known popularly as the "Sweet Sixteen")
- The Regional Finals (participating teams are known commonly as the "Elite Eight")
- The National Semi-finals (participating teams are referred to officially as the "Final Four")
- The National Championship

The motivation behind this project is that it is difficult to correctly predict the outcome of a sports game, especially group sports, like basketball. The ability to accurately predict the win/loss could help sports betting significantly. In basketball game data, with large datasets and detailed variables like the number of 2 pointers/3 pointers in a given game -- we, as data scientists, can utilize such extensively useful information and provide insight on the outcome of each game, which is invaluable to sports bettors. 

The data is from Kaggle Machine Learning Competition hosted by Google Cloud and NCAA 2018. It is a historical data collecting from year 1985 to 2018 (i.e. season 2017-2018, since this year's season is 2018-2019)[1].

[1] https://www.kaggle.com/c/mens-machine-learning-competition-2018/data

The original data from Kaggle Machine Learning Competitions had xx variables with xx observations. For this project, we have cleaned the dataset. 

```{r}
    # cleaned data
    train_X = read.csv("./train_X.csv")
    train_y = read.csv("./train_y.csv")
    
    test_X = read.csv("./test_X.csv")
    test_y = read.csv("./train_y.csv")
```

...about train_X, train_y, test_X, test_y
...comprensive intro to data

# Data Exploration
...summary stats
...viz

# Data Modeling 
...approaches
...goal

# Conclusion
..
..

As a group, you will submit files as you would for homework which include a .pdf/.html and .Rmd file. If your data is less than 10MB, you should submit the data too. Otherwise, you should provide a shared link to your actual cleaned R data (using, for example, google drive). Your report must contain the following:

    Project title
    Group Member Info
    Introduction and literature review (1 - 2 pages)
        Data source information (provide a link to your data source)
        You must have a comprehensive introduction of the data (no analysis) and the scientific goal
        You must review the literature (or relative sources) and report existing (possibly online) analyses results on this dataset
    Summary statistics and data visualization (less than 5 pages)
        You should provide a comprehensive summary of the data using tools we introduced
        Visualization is necessary for presenting the results
    Your proposed analysis (less than 10 pages)
        You should describe your approach and present your analysis results in a very comprehensive way
    Conclusion and discussion (1 - 2 pages)
        Summarize your scientific findings
        Address any potential pitfalls of your analysis, and discuss potential improvements (if you don’t have enough time to implement them)

