---
title: "Final Project"
author: "Taiga Hasegawa(taigah2)"
date: "2019/4/11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# unzip necessary files
unzip("./PlayByPlay_2010/Events_2010.csv.zip",exdir= "./PlayByPlay_2010") 
unzip("./PlayByPlay_2011/Events_2011.csv.zip",exdir= "./PlayByPlay_2011") 
unzip("./PlayByPlay_2012/Events_2012.csv.zip",exdir= "./PlayByPlay_2012") 
unzip("./PlayByPlay_2013/Events_2013.csv.zip",exdir= "./PlayByPlay_2013") 
unzip("./PlayByPlay_2014/Events_2014.csv.zip",exdir= "./PlayByPlay_2014") 
unzip("./PlayByPlay_2015/Events_2015.csv.zip",exdir= "./PlayByPlay_2015") 
unzip("./PlayByPlay_2016/Events_2016.csv.zip",exdir= "./PlayByPlay_2016") 
unzip("./PlayByPlay_2017/Events_2017.csv.zip",exdir= "./PlayByPlay_2017") 
```

```{r}
#FirstD1Season - the first season in our dataset that the school was a Division-I school
#LastD1Season - the last season in our dataset that the school was a Division-I school
teams=read.csv("DataFiles/Teams.csv")

#national semifinals are always on daynum=152, the "play-in" games are on days 134/135, Selection Sunday is on day 132
#Whichever region's name comes first alphabetically, that region will be Region W. And whichever Region plays against Region W in the national semifinals, that will be Region X. For the other two regions, whichever region's name comes first alphabetically, that region will be Region Y, and the other will be Region Z. 
Seasons=read.csv("DataFiles/Seasons.csv")

#the first character is either W, X, Y, or Z and the next two digits tells you the seed within the region. For play-in teams, there is a fourth character (a or b) to further distinguish the seeds
NCAATourneySeeds=read.csv("DataFiles/NCAATourneySeeds.csv")

#Regular Season games are simply defined to be all games played on DayNum=132 or earlier (DayNum=132 is Selection Sunday
#WLoc -If the winning team was the home team, this value will be "H". If the winning team was the visiting team, this value will be "A"
RegularSeasonCompactResults=read.csv("DataFiles/RegularSeasonCompactResults.csv")

#Because of the consistent structure of the NCAA® tournament schedule, you can actually tell what round a game was, depending on the exact DayNum. Thus:
#DayNum=134 or 135 (Tue/Wed) - play-in games to get the tournament field down to the final 64 teams
#DayNum=136 or 137 (Thu/Fri) - Round 1, to bring the tournament field from 64 teams to 32 teams
#DayNum=138 or 139 (Sat/Sun) - Round 2, to bring the tournament field from 32 teams to 16 teams
#DayNum=143 or 144 (Thu/Fri) - Round 3, otherwise known as "Sweet Sixteen", to bring the tournament field from 16 teams to 8 teams
#DayNum=145 or 146 (Sat/Sun) - Round 4, otherwise known as "Elite Eight" or "regional finals", to bring the tournament field from 8 teams to 4 teams
#DayNum=152 (Sat) - Round 5, otherwise known as "Final Four" or "national semifinals", to bring the tournament field from 4 teams to 2 teams
#DayNum=154 (Mon) - Round 6, otherwise known as "national final" or "national championship", to bring the tournament field from 2 teams to 1 champion team

NCAATourneyCompactResults=read.csv("DataFiles/NCAATourneyCompactResults.csv")

#WFGM - field goals made (by the winning team)
#WFGA - field goals attempted (by the winning team)
#WFGM3 - three pointers made (by the winning team)
#WFGA3 - three pointers attempted (by the winning team)
#WFTM - free throws made (by the winning team)
#WFTA - free throws attempted (by the winning team)
#WOR - offensive rebounds (pulled by the winning team)
#WDR - defensive rebounds (pulled by the winning team)
#WAst - assists (by the winning team)
#WTO - turnovers committed (by the winning team)
#WStl - steals (accomplished by the winning team)
#WBlk - blocks (accomplished by the winning team)
#WPF - personal fouls committed (by the winning team)
RegularSeasonDetailedResults=read.csv("DataFiles/RegularSeasonDetailedResults.csv")

NCAATourneyDetailedResults=read.csv("DataFiles/NCAATourneyDetailedResults.csv")

Cities=read.csv("DataFiles/Cities.csv")

GameCities=read.csv("DataFiles/GameCities.csv")

MasseyOrdinals=read.csv("MasseyOrdinals.csv")

Events_2010=read.csv("PlayByPlay_2010/Events_2010.csv")
Events_2011=read.csv("PlayByPlay_2011/Events_2011.csv")
Events_2012=read.csv("PlayByPlay_2012/Events_2012.csv")
Events_2013=read.csv("PlayByPlay_2013/Events_2013.csv")
Events_2014=read.csv("PlayByPlay_2014/Events_2014.csv")
Events_2015=read.csv("PlayByPlay_2015/Events_2015.csv")
Events_2016=read.csv("PlayByPlay_2016/Events_2016.csv")
Events_2017=read.csv("PlayByPlay_2017/Events_2017.csv")

Players_2010=read.csv("PlayByPlay_2010/Players_2010.csv")
Players_2011=read.csv("PlayByPlay_2011/Players_2011.csv")
Players_2012=read.csv("PlayByPlay_2012/Players_2012.csv")
Players_2013=read.csv("PlayByPlay_2013/Players_2013.csv")
Players_2014=read.csv("PlayByPlay_2014/Players_2014.csv")
Players_2015=read.csv("PlayByPlay_2015/Players_2015.csv")
Players_2016=read.csv("PlayByPlay_2016/Players_2016.csv")
Players_2017=read.csv("PlayByPlay_2017/Players_2017.csv")
#Delete the "TEAM" from playername column
Players_2010=Players_2010[Players_2010$PlayerName!="TEAM",]
Players_2011=Players_2011[Players_2011$PlayerName!="TEAM",]
Players_2012=Players_2012[Players_2012$PlayerName!="TEAM",]
Players_2013=Players_2013[Players_2013$PlayerName!="TEAM",]
Players_2014=Players_2014[Players_2014$PlayerName!="TEAM",]
Players_2015=Players_2015[Players_2015$PlayerName!="TEAM",]
Players_2016=Players_2016[Players_2016$PlayerName!="TEAM",]
Players_2017=Players_2017[Players_2017$PlayerName!="TEAM",]

TeamCoaches=read.csv("DataFiles/TeamCoaches.csv")

Conferences=read.csv("DataFiles/Conferences.csv")

TeamConferences=read.csv("DataFiles/TeamConferences.csv")

ConferenceTourneyGames=read.csv("DataFiles/ConferenceTourneyGames.csv")

SecondaryTourneyTeams=read.csv("DataFiles/SecondaryTourneyTeams.csv")

SecondaryTourneyCompactResults=read.csv("DataFiles/SecondaryTourneyCompactResults.csv")

```


```{r}
library(dplyr)
library(tidyr)
####get the score of each player every year#### 

##give the score to the player in the following way##
#assist=1
#block=1
#steal=1
#turnover=-1
#timeout, timeout_tv =0
#foul_pers=-1
#foul_tech=-1
#reb_off, reb_def, reb_dead=1
#sub_in, sub_ou=0
#made1_free=1,miss1_free=-1
#made2_dunk=1,miss2_dunk=0
#made2_tip=1,miss2_tip=0
#made2_lay=1,miss2_lay=0
#made2_jump=1,miss2_jump=0
#made3_jump=1,miss3_jump=0

events2010=dplyr::full_join(Events_2010,Players_2010,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2010$events_score=ifelse(events2010$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2010$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2010=group_by(events2010,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2011=dplyr::full_join(Events_2011,Players_2011,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2011$events_score=ifelse(events2011$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2011$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2011=group_by(events2011,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2012=dplyr::full_join(Events_2012,Players_2012,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2012$events_score=ifelse(events2012$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2012$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2012=group_by(events2012,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2013=dplyr::full_join(Events_2013,Players_2013,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2013$events_score=ifelse(events2013$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2013$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2013=group_by(events2013,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2014=dplyr::full_join(Events_2014,Players_2014,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2014$events_score=ifelse(events2014$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2014$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2014=group_by(events2014,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2015=dplyr::full_join(Events_2015,Players_2015,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2015$events_score=ifelse(events2015$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2015$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2015=group_by(events2015,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2016=dplyr::full_join(Events_2016,Players_2016,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2016$events_score=ifelse(events2016$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2016$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2016=group_by(events2016,PlayerName)%>%summarise(TotalScore=sum(events_score))
events2017=dplyr::full_join(Events_2017,Players_2017,by=c("Season","EventPlayerID"="PlayerID","EventTeamID"="TeamID"))
events2017$events_score=ifelse(events2017$EventType%in%c("assist","block","steal","reb_off","reb_def","reb_dead","made1_free","made2_dunk","made2_tip","made2_lay","made2_jump","made3_jump"),1,ifelse(events2017$EventType%in%c("turnover","foul_pers","foul_tech","miss1_free"),-1,0))
events2017=group_by(events2017,PlayerName)%>%summarise(TotalScore=sum(events_score))
```

```{r}
#merge Players file and events 
player_score_2010=dplyr::full_join(Players_2010,events2010,by="PlayerName")
player_score_2011=dplyr::full_join(Players_2011,events2011,by="PlayerName")
player_score_2012=dplyr::full_join(Players_2012,events2012,by="PlayerName")
player_score_2013=dplyr::full_join(Players_2013,events2013,by="PlayerName")
player_score_2014=dplyr::full_join(Players_2014,events2014,by="PlayerName")
player_score_2015=dplyr::full_join(Players_2015,events2015,by="PlayerName")
player_score_2016=dplyr::full_join(Players_2016,events2016,by="PlayerName")
player_score_2017=dplyr::full_join(Players_2017,events2017,by="PlayerName")
```

```{r}
#get the average player score of each team every year 
team_score_2010=group_by(player_score_2010,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2010$Season=2010
team_score_2010=team_score_2010[-dim(team_score_2010)[1],]
team_score_2011=group_by(player_score_2011,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2011$Season=2011
team_score_2011=team_score_2011[-dim(team_score_2011)[1],]
team_score_2012=group_by(player_score_2012,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2012$Season=2012
team_score_2012=team_score_2012[-dim(team_score_2012)[1],]
team_score_2013=group_by(player_score_2013,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2013$Season=2013
team_score_2013=team_score_2013[-dim(team_score_2013)[1],]
team_score_2014=group_by(player_score_2014,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2014$Season=2014
team_score_2014=team_score_2014[-dim(team_score_2014)[1],]
team_score_2015=group_by(player_score_2015,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2015$Season=2015
team_score_2015=team_score_2015[-dim(team_score_2015)[1],]
team_score_2016=group_by(player_score_2016,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2016$Season=2016
team_score_2016=team_score_2016[-dim(team_score_2016)[1],]
team_score_2017=group_by(player_score_2017,TeamID)%>%summarise(Teamscore=mean(TotalScore))
team_score_2017$Season=2017
team_score_2017=team_score_2017[-dim(team_score_2017)[1],]

team_score=rbind(team_score_2010,team_score_2011)
team_score=rbind(team_score,team_score_2012)
team_score=rbind(team_score,team_score_2013)
team_score=rbind(team_score,team_score_2014)
team_score=rbind(team_score,team_score_2015)
team_score=rbind(team_score,team_score_2016)
team_score=rbind(team_score,team_score_2017)
```

```{r}
####This dataset includes all the variables sampled every year####
dat_year=dplyr::full_join(TeamCoaches,TeamConferences,by=c("Season","TeamID"))
dat_year=dplyr::full_join(dat_year,team_score,by=c("Season","TeamID"))
dat_year=dat_year[,c(1,2,7)]
dat_year[dat_year$Season==2013,]
```


```{r}
####This dataset includes all the variables sampled every match####
NCAATourneyCompactResults_train=NCAATourneyCompactResults[NCAATourneyCompactResults$Season<2014,]
NCAATourneyCompactResults_test=NCAATourneyCompactResults[NCAATourneyCompactResults$Season>=2014,]
NCAATourneyDetailedResults_train=NCAATourneyDetailedResults[NCAATourneyDetailedResults$Season<2014,]
NCAATourneyDetailedResults_test=NCAATourneyDetailedResults[NCAATourneyDetailedResults$Season>=2014,]


Compact_train=rbind(RegularSeasonCompactResults,NCAATourneyCompactResults_train)
Compact_test=NCAATourneyCompactResults_test
Details_train=rbind(RegularSeasonDetailedResults,NCAATourneyDetailedResults_train)
Details_test=NCAATourneyDetailedResults_test

#I uesd left full because I want to keep the all row in both dataset
Results_train=dplyr::full_join(Compact_train,Details_train,by=c("Season","DayNum","WTeamID","LTeamID","WScore","LScore","WLoc","NumOT"))

Results_test=dplyr::full_join(Compact_test,Details_test,by=c("Season","DayNum","WTeamID","LTeamID","WScore","LScore","WLoc","NumOT"))

spread_rank=spread(MasseyOrdinals,key="SystemName",value="OrdinalRank")

dat_day_train=left_join(Results_train,spread_rank,by=c("Season","DayNum"="RankingDayNum","WTeamID"="TeamID"))
dat_day_train=left_join(dat_day_train,spread_rank,by=c("Season","DayNum"="RankingDayNum","LTeamID"="TeamID"))

#rate data only has the date before DayNum=134. This is why, I want to regard the rate of the DayNum=133 as the rate for the NCAATourney
spread_rank_for_test=spread_rank[spread_rank$RankingDayNum==133,]

dat_day_test=left_join(Results_test,spread_rank_for_test,by=c("Season","WTeamID"="TeamID"))
dat_day_test=left_join(dat_day_test,spread_rank_for_test,by=c("Season","LTeamID"="TeamID"))

dat_day_test=dat_day_test[,c(-35,-202)]
#70T.x~ZAM.x is the ranking for WTeam
#70T.y~ZAM.y is the ranking for LTeam
colnames(dat_day_test)
```

```{r}
dat_day_train_1=dat_day_train
colnames(dat_day_train_1)[3]="TeamID1"
colnames(dat_day_train_1)[5]="TeamID2"
colnames(dat_day_train_1)[4]="Team1_score"
colnames(dat_day_train_1)[6]="Team2_score"
for(i in 9:21){
  colnames(dat_day_train_1)[i]=paste0("Team1_",substr(colnames(dat_day_train_1)[i],2,nchar(colnames(dat_day_train_1)[i])))
}
for(i in 22:34){
  colnames(dat_day_train_1)[i]=paste0("Team2_",substr(colnames(dat_day_train_1)[i],2,nchar(colnames(dat_day_train_1)[i])))
}
for(i in 35:200){
  colnames(dat_day_train_1)[i]=paste0("Team1_",substr(colnames(dat_day_train_1)[i],1,nchar(colnames(dat_day_train_1)[i])-1))
}
for(i in 201:366){
  colnames(dat_day_train_1)[i]=paste0("Team2_",substr(colnames(dat_day_train_1)[i],1,nchar(colnames(dat_day_train_1)[i])-1))
}
winners=dat_day_train_1
winners$Result=1.0
```

```{r}
dat_day_train_2=dat_day_train
colnames(dat_day_train_2)[3]="TeamID2"
colnames(dat_day_train_2)[5]="TeamID1"
colnames(dat_day_train_2)[4]="Team2_score"
colnames(dat_day_train_2)[6]="Team1_score"
for(i in 9:21){
  colnames(dat_day_train_2)[i]=paste0("Team2_",substr(colnames(dat_day_train_2)[i],2,nchar(colnames(dat_day_train_2)[i])))
}
for(i in 22:34){
  colnames(dat_day_train_2)[i]=paste0("Team1_",substr(colnames(dat_day_train_2)[i],2,nchar(colnames(dat_day_train_2)[i])))
}
for(i in 35:200){
  colnames(dat_day_train_2)[i]=paste0("Team2_",substr(colnames(dat_day_train_2)[i],1,nchar(colnames(dat_day_train_2)[i])-1))
}
for(i in 201:366){
  colnames(dat_day_train_2)[i]=paste0("Team1_",substr(colnames(dat_day_train_2)[i],1,nchar(colnames(dat_day_train_2)[i])-1))
}
losers=dat_day_train_2
losers$Result=0.0
```

```{r}
dat_day_test_1=dat_day_test
colnames(dat_day_test_1)[3]="TeamID1"
colnames(dat_day_test_1)[5]="TeamID2"
colnames(dat_day_test_1)[4]="Team1_score"
colnames(dat_day_test_1)[6]="Team2_score"
winners_test=dat_day_test_1
winners_test$Result=1.0
```

```{r}
dat_day_test_2=dat_day_test
colnames(dat_day_test_2)[3]="TeamID1"
colnames(dat_day_test_2)[5]="TeamID2"
colnames(dat_day_test_2)[4]="Team1_score"
colnames(dat_day_test_2)[6]="Team2_score"
losers_test=dat_day_test_2
losers_test$Result=0.0
```


```{r}
train=rbind(winners,losers)
test=rbind(winners_test,losers_test)
```


```{r}

#Points Winning/Losing Team
train$WPts=2*train$Team1_FGM+train$Team1_FGM3+train$Team1_FTM
train$LPts=2*train$Team2_FGM3+train$Team2_FGM3+train$Team2_FTM
#Calculate Winning/losing Team Possesion Feature
wPos=train$Team1_FGM+train$Team1_FGM+train$Team1_FTM-train$Team1_OR
lPos=train$Team2_FGA+train$Team2_TO+0.44*train$Team2_FTA-train$Team2_OR
#two teams use almost the same number of possessions in a game
#(plus/minus one or two - depending on how quarters end)
#so let's just take the average
train$Pos=(wPos+lPos)/2
#Offensive efficiency (OffRtg) = 100 x (Points / Possessions)
train$WOffRtg=100*(train$WPts/train$Pos)
train$LOffRtg=100*(train$LPts/train$Pos)
#Defensive efficiency (DefRtg) = 100 x (Opponent points / Opponent possessions)
train$WDefRtg=train$LOffRtg
train$LDefRtg=train$WOffRtg
#Net Rating = Off.Rtg - Def.Rtg
train$WNetRtg=train$WOffRtg-train$WDefRtg
train$LNetRtg=train$LOffRtg-train$LDefRtg
#Assist Ratio : Percentage of team possessions that end in assists
train$WAstR=100*train$Team1_Ast/(train$Team1_FGA + 0.44*train$Team1_FTA+ train$Team1_Ast + train$Team1_TO)
train$LAstR=100*train$Team2_Ast/(train$Team2_FGA + 0.44*train$Team2_FTA+ train$Team2_Ast + train$Team2_TO)
#Turnover Ratio: Number of turnovers of a team per 100 possessions used.
#(TO * 100) / (FGA + (FTA * 0.44) + AST + TO)
train$WTOR=100 * train$Team1_TO / (train$Team1_FGA + 0.44*train$Team1_FTA + train$Team1_Ast + train$Team1_TO)
train$LTOR=100 * train$Team2_TO / (train$Team2_FGA + 0.44*train$Team2_FTA + train$Team2_Ast + train$Team2_TO)
#The Shooting Percentage : Measure of Shooting Efficiency (FGA/FGA3, FTA)
train$WTSP=100 * train$WPts / (2 * (train$Team1_FGA + 0.44*train$Team1_FTA))
train$LTSP=100 * train$LPts / (2 * (train$Team2_FGA + 0.44*train$Team2_FTA))
#eFG% : Effective Field Goal Percentage adjusting for the fact that 3pt shots are more valuable 
train$WeFGP=(train$Team1_FGM + 0.5 *train$Team1_FGM3) / train$Team1_FGA
train$LeFGP=(train$Team2_FGM + 0.5 *train$Team2_FGM3) / train$Team2_FGA
#FTA Rate : How good a team is at drawing fouls.
train$WFTAR = train$Team1_FTA / train$Team1_FGA
train$LFTAR = train$Team2_FTA / train$Team2_FGA
#OREB% : Percentage of team offensive rebounds
train$WORP = train$Team1_OR / (train$Team1_OR + train$Team2_DR)
train$LORP = train$Team2_OR / (train$Team1_OR + train$Team2_DR)
#DREB% : Percentage of team defensive rebounds
train$WDRP = train$Team1_DR / (train$Team1_DR + train$Team2_OR )
train$LDRP=train$Team2_DR / (train$Team2_DR + train$Team1_OR )
#REB% : Percentage of team total rebounds
train$WRP=(train$Team1_DR + train$Team1_OR) / (train$Team1_DR + train$Team1_OR + train$Team2_DR + train$Team2_OR)
train$LRP=(train$Team2_DR + train$Team2_OR) / (train$Team1_DR + train$Team1_OR + train$Team2_DR + train$Team2_OR)

train$Wranking=apply(train[,35:200],1,function(x) mean(x,na.rm=TRUE))
train$Lranking=apply(train[,201:366],1,function(x) mean(x,na.rm=TRUE))
train=train[,c(-9:-366)]
```

```{r}
test$Wranking=apply(test[,35:200],1,function(x) mean(x,na.rm=TRUE))
test$Lranking=apply(test[,201:366],1,function(x) mean(x,na.rm=TRUE))
test=test[,c(-4,-6,-8:-366)]
#We have to remove the value from WFGM~LPF because otherwise it will cause data leakage

#Instead substitute the previous mean value for the removed value  
test
```


```{r}
train=dplyr::left_join(train,dat_year,by=c("Season","TeamID1"="TeamID"))
train_X=train[,c(-4,-6,-8,-9)]
train_y=train[,9]
colnames(train_X)[6:30]
```
```{r}
train_X
weighted_mean=function(dat,colnum){
  a=dat%>%group_by(TeamID1)%>%summarise(mean(colnames(dat)[colnum],na.rm=TRUE))
  b=dat%>%group_by(TeamID1,TeamID2)%>%summarise(mean(colnames(dat)[colnum],na.rm=TRUE))
  c=dplyr::left_join(b,a,by="TeamID1")
  d=c[,c(3,4)]
  c$weighted_mean=apply(d,1,FUN=mean,na.rm=TRUE)
}
weighted_mean(dat=train_X,6)
```

```{r}
library(glmnet)
scaled_train=data.frame(scale(train_X[,-5]))
scaled_train$WLoc=train_X$WLoc
scaled_train$y=train_y
scaled_train
logistic=glm(y~.,data = scaled_train_x,family = binomial())
summary(logistic)
```

```{r}
MasseyOrdinals_Prelim2018=read.csv("PrelimData2018/MasseyOrdinals_Prelim2018.csv")
tail(MasseyOrdinals_Prelim2018)
```

